// DATA SOURCES
export enum DATABASE_SOURCES {
  DATA_SOURCE = 'DATA_SOURCE', // MASTER DATA SOURCE
}
// REPOSITORY PROVIDERS
export enum DB_CONST_REPOSITORY {
  USER = 'USER_REPOSITORY',
  USER_HISTORY = 'USER_HISTORY_REPOSITORY',
  USER_LOGIN_HISTORY = 'USER_LOGIN_HISTORY_REPOSITORY',
  FEED = 'FEED',
  FEED_IMAGE = 'FEED_IMAGE',
  COMMENT = 'COMMENT',
  COMMENT_REPLY = 'COMMENT_REPLY',
  MAPPER_USER_FOLLOW = 'MAPPER_USER_FOLLOW',
}
